### ISSUE TITLE
"'Name' can't be empty" while adding task

### ISSUE THREAD

**Issue by flemmingss** [isabellaalstrom/lovelace-grocy-chores-card#162]
This is the same as issue #159 , it is completed, but I still have the same issue.
![image](https://github.com/user-attachments/assets/947236e3-6b95-4c54-ab17-61efb9f8a130)

Core 2025.1.2
Supervisor 2024.12.3
HACS 2.0.2

```
type: custom:grocy-chores-card
entity:
  - sensor.grocy_chores
  - sensor.grocy_tasks
title: Todo
show_quantity: 5
show_assigned: true
show_overflow: true
show_chores_without_due: true
show_tasks_without_due: true
show_create_task: true
use_icons: true
use_long_date: true
due_in_days_threshold: 7
use_24_hours: true
hide_text_with_no_data: true
```

**Comment by BoneZer** [comment]
Okay I checked a bit more:
The code in the repo was fine. Version 3.8.2. didn't use the paper-input at all. I have no idea how we got the same error, @flemmingss but for me it was solved when I removed the card and added it again via hacs

**Comment by Sceptorrh** [comment]
Hey! I sadly have the same Issue. Removing and reinstalling trough hacs had no effect. I also noticed that 'due_in_days_threshold: 0' is not working for me. It still shows all tasks/chores regardless of its due date
